apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- security-context-pod.yaml
replacements:
- source:
    kind: Pod
    name: security-context
    fieldPath: spec.containers.0.securityContext
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.*.securityContext
    - spec.template.spec.initContainers.[name=^.+$].securityContext
    options:
      create: true
- source:
    kind: Pod
    name: security-context
    fieldPath: spec.containers.0.securityContext
  targets:
  - select:
      kind: StatefulSet
    fieldPaths:
    - spec.template.spec.containers.*.securityContext
    - spec.template.spec.initContainers.[name=^.+$].securityContext
    options:
      create: true
