namespace: myapp
secretGenerator:
  - name: app-secret
    options:
      disableNameSuffixHash: true
    envs:
    - secrets.env
  - name: dockerconfigjson-github-com
    options:
      disableNameSuffixHash: true
    type: kubernetes.io/dockerconfigjson
    files:
    - .dockerconfigjson
